---
- name: Load common variables
  include_vars:
    file: "../config/defaults/main.yml"

- name: Ensure Free5GC namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ core_ns }}"
    state: present

- name: Create cert-pvc for Free5GC
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cert-pvc
        namespace: "{{ core_ns }}"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: openebs-hostpath
        volumeMode: Filesystem

- name: Wait for cert-pvc to be Bound
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    namespace: "{{ core_ns }}"
    name: cert-pvc
  register: pvc_info
  until: pvc_info.resources[0].status.phase == "Bound"
  retries: 20
  delay: 3

- name: Deploy Free5GC using Helm
  when: rru == 'rfsim'
  kubernetes.core.helm:
    name: free5gc
    chart_ref: "{{ [repo_dest, 'charts', 'free5gc'] | path_join }}"
    release_namespace: "{{ core_ns }}"
    state: present
    wait: true
    atomic: true
    timeout: 1200s
    values:
      nodeSelector:
        kubernetes.io/hostname: "{{ core_node_name }}"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "{{ core_node_name }}"
      upf:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
            - SYS_MODULE
