#!/usr/bin/env python3
# Generated by Ansible from 5G profile: {{ fiveg_profile | default('default') }}
# DO NOT EDIT MANUALLY
#
# UE Type Detection:
#   Uses imsi_suffix from profile to track which UEs are rfsim vs physical
#   - imsi_suffix in rfsim_suffixes list → rfsim (simulé) → full sequenceNumber
#   - otherwise → physical (réel) → minimal sequenceNumber

import argparse
import free5gc_db

parser = argparse.ArgumentParser()
parser.add_argument("-m", "--mongo", help="Mongodb address", default='mongodb')
parser.add_argument("-a", "--action", help="Action to be performed (list|add|clean)", default='list')
args = parser.parse_args()

free5gc_instance = free5gc_db.Free5gc(args.mongo, 27017)

PLMN = "{{ profile.plmn.mcc }}{{ profile.plmn.mnc }}"

# Slices definition from profile
SLICES = {
{% for slice in profile.slices %}
    "{{ slice.name }}": {
        "sst": {{ slice.sst | int }},
        "sd": "{{ 'ffffff' if slice.sd == 'EMPTY' else '%06x' | format(slice.sd | int(base=16)) }}",
        "sd_key": "{{ '%02x%s' | format(slice.sst | int, 'ffffff' if slice.sd == 'EMPTY' else '%06x' | format(slice.sd | int(base=16))) }}",
        "dnn": "{{ slice.dnn }}",
        "uplink": "{{ slice.bandwidth.uplink | regex_replace('([0-9]+)([A-Za-z]+)', '\\1 \\2') }}",
        "downlink": "{{ slice.bandwidth.downlink | regex_replace('([0-9]+)([A-Za-z]+)', '\\1 \\2') }}",
        "five_qi": {{ slice.qos.five_qi | int }},
        "arp_priority": {{ slice.qos.arp.priority_level | int }},
    },
{% endfor %}
}

# Build a map of imsi_suffix → ue_name for type detection
# This allows us to identify rfsim vs physical UEs by their suffix
RFSIM_SUFFIXES = {
{% for ue_name, ue in profile.ues.items() %}
{% if ue_name.lower().startswith("uesim") %}
    "{{ ue.imsi_suffix }}": "{{ ue_name }}",  # rfsim UE
{% endif %}
{% endfor %}
}

# UEs definition from profile
UES = {
{% for ue_name, ue in profile.ues.items() %}
    "{{ ue_name }}": {
        "imsi": "{{ profile.plmn.mcc }}{{ profile.plmn.mnc }}{{ ue.imsi_suffix }}",
        "imsi_suffix": "{{ ue.imsi_suffix }}",
        "slice": "{{ ue.slice }}",
        "key": "{{ profile.security.full_key }}",
        "opc": "{{ profile.security.opc }}",
    },
{% endfor %}
}


def get_ue_type(imsi_suffix):
    """
    Detect UE type based on imsi_suffix.
    This suffix comes from the 5G profile where uesim* UEs are defined.
    - If suffix is in RFSIM_SUFFIXES → rfsim (simulé)
    - Otherwise → physical (réel)
    """
    return "rfsim" if imsi_suffix in RFSIM_SUFFIXES else "physical"


def build_subscriber_data(ue_name, ue):
    imsi_full = f"imsi-{ue['imsi']}"
    slice_name = ue["slice"]
    s = SLICES[slice_name]
    sd = s["sd"]
    sst = s["sst"]
    sd_key = s["sd_key"]
    snssai_key = sd_key
    dnn = s["dnn"]
    is_empty_sd = (sd == "ffffff")
    
    # Detect UE type from imsi_suffix
    ue_type = get_ue_type(ue["imsi_suffix"])

    # Build snssai infos — add empty-sd alias for EMPTY slices
    subscribed_snssai_infos = {
        snssai_key: {'dnnInfos': [{'dnn': dnn}]}
    }
    sm_policy_snssai_data = {
        snssai_key: {
            'smPolicyDnnData': {dnn: {'dnn': dnn}},
            'snssai': {'sd': sd, 'sst': float(sst)}
        }
    }
    if is_empty_sd:
        empty_key = "%02x" % sst  # "01" — no SD
        subscribed_snssai_infos[empty_key] = {'dnnInfos': [{'dnn': dnn}]}
        sm_policy_snssai_data[empty_key] = {
            'smPolicyDnnData': {dnn: {'dnn': dnn}},
            'snssai': {'sd': '', 'sst': float(sst)}
        }

    # Build sequenceNumber based on UE type
    if ue_type == "rfsim":
        # rfsim UEs: full SQN structure with scheme and lastIndexes
        sequence_number = {
            'sqn': '000000000020',
            'sqnScheme': 'NON_TIME_BASED',
            'lastIndexes': {'ausf': 0}
        }
    else:
        # Physical UEs: minimal SQN structure (no sqnScheme, no lastIndexes)
        sequence_number = {
            'sqn': '000000000020',
        }

    return {
        'subscriptionData.provisionedData.smfSelectionSubscriptionData': [{
            'servingPlmnId': PLMN,
            'subscribedSnssaiInfos': subscribed_snssai_infos,
            'ueId': imsi_full
        }],
        'subscriptionData.provisionedData.smData': [{
            'dnnConfigurations': {
                dnn: {
                    '5gQosProfile': {
                        '5qi': float(s["five_qi"]),
                        'arp': {
                            'preemptCap': '',
                            'preemptVuln': '',
                            'priorityLevel': float(s["arp_priority"])
                        },
                        'priorityLevel': float(s["arp_priority"])
                    },
                    'pduSessionTypes': {
                        'allowedSessionTypes': ['IPV4'],
                        'defaultSessionType': 'IPV4'
                    },
                    'sessionAmbr': {
                        'downlink': s["downlink"],
                        'uplink': s["uplink"]
                    },
                    'sscModes': {
                        'allowedSscModes': ['SSC_MODE_2', 'SSC_MODE_3'],
                        'defaultSscMode': 'SSC_MODE_1'
                    }
                }
            },
            'servingPlmnId': PLMN,
            'singleNssai': {'sd': sd, 'sst': float(sst)},
            'ueId': imsi_full
        }],
        'policyData.ues.smData': [{
            'smPolicySnssaiData': sm_policy_snssai_data,
            'ueId': imsi_full
        }],
        'policyData.ues.amData': [{
            'subscCats': ['free5gc'],
            'ueId': imsi_full
        }],
        'subscriptionData.provisionedData.amData': [{
            'gpsis': [f'msisdn-0900000000'],
            'nssai': {
                'defaultSingleNssais': [{'sd': sd, 'sst': float(sst)}]
            },
            'servingPlmnId': PLMN,
            'subscribedUeAmbr': {'downlink': '2 Gbps', 'uplink': '1 Gbps'},
            'ueId': imsi_full
        }],
        'subscriptionData.authenticationData.authenticationSubscription': [{
            'authenticationManagementField': '8000',
            'authenticationMethod': '5G_AKA',
            'encPermanentKey': ue['key'],
            'encOpcKey': ue['opc'],
            'sequenceNumber': sequence_number,
            'ueId': imsi_full
        }],
    }



if args.action == 'list':
    subscribers_data = free5gc_instance.get_subscribers()
    for key, value in subscribers_data.items():
        print(key)
        for item in value:
            print(item)
        print()
    print("Summary:")
    for key, value in subscribers_data.items():
        print(f"{key}: {len(value)}")

elif args.action == 'clean':
    free5gc_instance.delete_all_subscribers()
    print("All subscribers deleted.")

elif args.action == 'add':
    rfsim_count = 0
    physical_count = 0
    
    for ue_name, ue in UES.items():
        subscriber_data = build_subscriber_data(ue_name, ue)
        result = free5gc_instance.add_subscriber(subscriber_data)
        
        ue_type = get_ue_type(ue["imsi_suffix"])
        if ue_type == "rfsim":
            rfsim_count += 1
            marker = "[rfsim]"
        else:
            physical_count += 1
            marker = "[physical]"
        
        if result:
            print(f"✓ {marker} Subscriber {ue_name} ({ue['imsi']}) added.")
        else:
            print(f"✗ {marker} Error adding subscriber {ue_name}.")
    
    print()
    print(f"Summary: {rfsim_count} rfsim UEs, {physical_count} physical UEs added.")
