---
duration: "{{ nuttcp_duration | default(30) }}"
sleep: "{{ nuttcp_sleep | default(5) }}"
# tcp_bandwidth: "0" # Unclear whether a 0 value works as "no limit" for nuttcp.  Simply don't use any -R option to send without a limit
udp_bandwidth: "50m" # Note that "m/g" suffix should be lowercase, unlike iPerf.  Default is "k" if no suffix specified
async_stagger: 0

nuttcp_scenarios:
  - {protocol: "tcp", direction: "up", extra_args: "-v -t"}
  - {protocol: "tcp", direction: "down", extra_args: "-v -r"}
  - {protocol: "udp", direction: "up", extra_args: "-v -u -R {{ udp_bandwidth }} -t"}
  - {protocol: "udp", direction: "down", extra_args: "-v -u -R {{ udp_bandwidth }} -r"}