---
#
# --- Visualization setup ---
#

- name: Setup first fit node for spectrum visualization (uhd_fft)
  hosts: faraday

  pre_tasks:

    - name: Set fit_node safely if group exists
      set_fact:
        fit_node: "{{ groups['fit_nodes'] | first }}"
      when: groups['fit_nodes'] | default([]) | length > 0

    - name: Debug selected fit_node
      debug:
        msg: "Using FIT node: {{ fit_node }}"
      when: fit_node is defined

  roles:
    - role: scenarios/interference/setup
      when: fit_node is defined
    - role: scenarios/interference/watch
      when: fit_node is defined

#
# --- Noise generation setup ---
#
- name: Setup second fit node on R2Lab for noise genaration
  hosts: faraday
  vars:
    fit_node: "{{ groups['fit_nodes'][1] }}"
    fit_number: "{{ hostvars[fit_node].fit_number }}"
    fit_usrp: "{{ hostvars[fit_node].fit_usrp }}"
  roles:
    - role: scenarios/interference/setup
      when: hostvars[groups['faraday'][0]].interference_usrp == 'fit'

- name: Setup interference USRP on R2Lab
  hosts: faraday
  vars:
    rru: "{{ hostvars[groups['faraday'][0]].interference_usrp }}"
  roles:
    - role: r2lab/rru
      when: hostvars[groups['faraday'][0]].interference_usrp in ['n300', 'n320']

#
# --- UE setup (first UE on the list) ---
#
- name: Connect and configure routes on the first R2lab UE
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Connect first UE via connect_ue tasks
      include_tasks: ../roles/scenarios/iperf/ue-to-target_server/tasks/connect_ue.yml
      vars:
        current_ue: "{{ groups['qhats'][0] }}"
        fiveg_profile: default
        ignore_task_errors: true
        target_server: "{{ core_node }}"
        target_server: "{{ hostvars[groups['core_node'][0]].ip }}"

