---

#
# --- Noise generation setup ---
#
- name: Set up fit node for noise generation if any
  hosts: faraday

  pre_tasks:
    - name: Set fit_node for noise
      set_fact:
        fit_node: "{{ groups['fit_nodes'][0] }}"
      when:
        - groups['fit_nodes'] | length > 0
        - hostvars.get(groups['faraday'][0], {}).get('interference_usrp') == 'fit'

    - name: Set fit details for noise
      set_fact:
        fit_number: "{{ hostvars[fit_node].fit_number }}"
        fit_usrp: "{{ hostvars[fit_node].fit_usrp }}"
      when: fit_node is defined

  roles:
    - role: scenarios/interference/setup
      when:
        - fit_node is defined
        - fit_number is defined
        - fit_usrp is defined

- name: Set up interference USRP on R2Lab
  hosts: faraday
  vars:
    rru: "{{ hostvars.get(groups['faraday'][0], {}).get('interference_usrp') }}"
  roles:
    - role: r2lab/rru
      when: hostvars[groups['faraday'][0]].interference_usrp in ['n300', 'n320']

#
# --- Visualization setup ---
#

- name: Set up fit node for spectrum visualization (uhd_fft)
  hosts: faraday

  pre_tasks:

    - name: Set fit_index
      set_fact:
        fit_index: >-
          {{
            1 if (
              hostvars.get(groups['faraday'][0], {}).get('interference_usrp') == 'fit'
              and groups.get('fit_nodes', []) | length > 1
            ) else 0
          }}
      when: groups['fit_nodes'] | length > 0

    - name: Set fit_node
      set_fact:
        fit_node: "{{ groups['fit_nodes'][fit_index | int] }}"
      when:
        - fit_index is defined
        - groups['fit_nodes'] | length > 0

    - name: Set fit details
      set_fact:
        fit_number: "{{ hostvars[fit_node].fit_number }}"
        fit_usrp: "{{ hostvars[fit_node].fit_usrp }}"
      when: fit_node is defined

  roles:
    - role: scenarios/interference/setup
      when:
        - fit_node is defined
        - fit_number is defined
        - fit_usrp is defined

#
# --- UE setup (first UE on the list) ---
#
- name: Connect and configure routes on the first R2lab UE
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Connect first UE via connect_ue tasks
      include_tasks: ../roles/scenarios/iperf/ue-to-target_server/tasks/connect_ue.yml
      vars:
        current_ue: "{{ groups['qhats'][0] }}"
        fiveg_profile: default
        ignore_task_errors: true
        target_server: "{{ hostvars[groups['core_node'][0]].ip }}"
